### PR TITLE
Allow league/uri ^7

### PR DESCRIPTION
**Pull request by nicolas-grekas**
So that psr/http-message 2.* can be installed (see #328)

### CODE REVIEW

**Comment by kelunik** [comment]
Let's wait for the stable release. 🙂

**Comment by kelunik** [comment]
@nicolas-grekas Could you please re-trigger the pipeline?

**Comment by nicolas-grekas** [comment]
force-pushed but still failing

**Comment by kelunik** [comment]
@nicolas-grekas Thanks! We've fixed the breaking change in hpack in https://github.com/amphp/hpack/releases/tag/v3.1.3. There's one remaining test failure, but that seems unrelated.

**Pull request merged**
