### PR TITLE
Immutable client

### PR DESCRIPTION
**Pull request by trowski**
Extension of #198. @kelunik thoughts on the last commit?

### CODE REVIEW

**Comment by enumag** [comment]
:+1: Yeah, immutable client would be really nice. I could then have it as a service in my dependency injection container and add additional interceptors as needed without touching the service itself. Ofc I can still do it with cloning but this feels better.

**Comment by kelunik** [comment]
@trowski Could you modify this PR to only contain the immutability change, please? I'd like to get this merged, as #200 will probably depend on this.

**Comment by trowski** [comment]
@kelunik So remove the follow redirects portion? I think that should be done as well, but I can put that in another PR after this is merged. I can rebase after #198 is merged, since that has diverged a bit now too.

**Comment by trowski** [comment]
Rebasing on master was simple, so I did that quickly. Will need to rebase #198 on this after merging.

**Pull request merged**
