### PR TITLE
Clone request before sending in FollowRedirects

### LINKED ISSUE #332: If a response redirects, it sends back raw gzip instead of decoded content
Somewhere between beta 9 and 11, but probably in beta 11, redirects cause raw gzip instead of decoded content to be emitted in the body.

```php
$client = HttpClientBuilder::buildDefault();
$response = $client->request(new Request('https://steamcommunity.com/profiles/76561197960287930')); // redirects
$body = $response->getBody()->read(); // gzip
```

```php
$client = HttpClientBuilder::buildDefault();
$response = $client->request(new Request('https://steamcommunity.com/id/GabeLoganNewell/')); // canonical URL (doesn't redirect)
$body = $response->getBody()->read(); // HTML
```

### PR DESCRIPTION
**Pull request by trowski**
This clones the request before sending on the client to avoid copying values set by subsequent interceptors.

Fixes #332.

### CODE REVIEW

**Review by kelunik — APPROVED** [review]

**Comment by Bilge** [comment]
I think this case needs a test.

**Comment by kelunik** [comment]
Good idea, do you have time to contribute one?

**Comment by Bilge** [comment]
No 🙂

**Comment by kelunik** [comment]
You might stay our test then. 😆

**Comment by Bilge** [comment]
OK but this still needs a tag, at least.

**Pull request merged**
