### PR TITLE
Forbid serialization for most classes

### PR DESCRIPTION
**Pull request by kelunik**
Maybe we should even make this a trait?

### CODE REVIEW

**Comment by trowski** [comment]
Is this really necessary? We probably should prevent cloning of a lot of classes too, but we don't currently prevent that either.

**Comment by trowski** [comment]
Another thought: Are there libraries that assume that a public `__sleep` method means the class *is* serializable? Another approach is declaring the method private.

**Comment by kelunik** [comment]
I think it doesn't hurt to forbid it and might prevent issues because people accidentally do dump things, e.g. passing things to parallel that shouldn't be serialized.

I've taken the approach from https://ocramius.github.io/extremely-defensive-php/#/, might be better to simply make the method private to have it better detectable for static analysis.

**Comment by trowski** [comment]
Should we add a couple traits like `ForbidSerialization` and `ForbidCloning` to `amphp/amp` so we can reuse them everywhere?

**Comment by kelunik** [comment]
@trowski Seems fine with me. Can traits have final methods?

**Comment by trowski** [comment]
Good question, [seems they can](https://3v4l.org/Clhck).

**Comment by enumag** [comment]
Seems unnecessary to me.

**Pull request closed without merging**
