### PR TITLE
Set used protocol version to request

### PR DESCRIPTION
**Pull request by kelunik**

### CODE REVIEW

**Comment by trowski** [comment]
What's the purpose? `Response::getProtocolVersion()` tells you what protocol version was used.

**Comment by kelunik** [comment]
@trowski With HTTP/1.0, you might get a HTTP/1.1 response, no?

**Comment by trowski** [comment]
Yes, you might receive a 1.1 response, but how does setting it on the `Request` object help?

**Comment by kelunik** [comment]
@trowski It allow printing the request as sent.

**Pull request merged**
